service: api-tts

provider:
  name: aws
  runtime: python3.9
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v1_tts:
    handler: post.v1_tts
    events:
      - httpApi:
          path: /v1/tts
          method: post

